### PR TITLE
Introduce Item.severity

### PR DESCRIPTION
**Pull request by shlomizadok**
fish #3

Wasn't sure if it fits into Item model or Rule model. Chose Item model as it may be used also in group.

### CODE REVIEW

**Comment by isimluk** [comment]
Conflicts after I merged #1.

**Comment by shlomizadok** [comment]
@isimluk - thanks. Will rebase after #2 is merged :+1:

**Comment by shlomizadok** [comment]
@isimluk - rebased. Thanks

**Comment by isimluk** [comment]
```
lib/openscap/xccdf/item.rb:69:13: C: Use 2 spaces for indentation in a hash, relative to the start of the line where the left curly brace is.
            :xccdf_level_not_defined => 'Not defined',
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/openscap/xccdf/item.rb:113:7: C: Indent the first parameter one step more than the start of the previous line.
      :xccdf_level_not_defined, 0,
      ^^^^^^^^^^^^^^^^^^^^^^^^
```

Please fix the `rubocop`. Rest of the code is compliant with rubocop, and I don't want to introduce these warnings.

Thanks!

**Comment by shlomizadok** [comment]
@isimluk - fixed rubocop and moved severity to Rule.

**Comment by isimluk** [comment]
perfect. thanks!

**Pull request merged**
