### PR TITLE
Introduce Item.references

### PR DESCRIPTION
**Pull request by shlomizadok**
Fish #4
(was a bit difficult to catch...)

### CODE REVIEW

**Comment by isimluk** [comment]
Conflicts after I merged #1, please rebase.

**Comment by shlomizadok** [comment]
@isimluk - let's play this one by one... will rebase after #3 is merged

**Comment by shlomizadok** [comment]
@isimluk - I hope this is what you meant for.

**Comment by shlomizadok** [comment]
@isimluk - I have created this [little gem](https://github.com/shlomizadok/openscap_report_parser/blob/master/lib/openscap_report_parser/openscap_report_parser.rb) which parses the report and returns it as json.
I thought it would be easier to fetch the references as a hash, however if you feel this is not the case, I can parse it when creating the json

**Comment by isimluk** [comment]
I understand, you have a single use case in mind.

However, ruby-openscap is a generic binding library on top of libopenscap. I think it makes sense for a libraty to return results, which are useful in general, not only in a single use case.

You can use then use Visitor pattern to build json from the hash of objects.

**Comment by isimluk** [comment]
I have an idea!

What if you put 

```
    def to_s
       { :title => @title, 
         :href => @href
       }.to_json
    end
```

into the Xccdf::Reference class? Would you be able to use it? When serializing hash to json?

**Comment by shlomizadok** [comment]
I like your idea, however I chose to use `to_hash`, as it will represent a broader use for the data. It may be parsed as JSON, csv, etc.

**Comment by isimluk** [comment]
Thanks!!

**Pull request merged**
