### PR TITLE
Introduce Rule.fixes

### PR DESCRIPTION
**Pull request by shlomizadok**
fish #5
This was definitely the hardest to achieve.
(Thanks for the giving me the hook!)

### CODE REVIEW

**Comment by isimluk** [comment]
Conflicts after I merged #1, please rebase.

**Comment by shlomizadok** [comment]
But don't we concat them for the purpose of display?
Ain't this supposed to display all the fixes for rule?

**Comment by shlomizadok** [comment]
@isimluk - maybe concat them by `xccdf_fix_get_system` ?

**Comment by isimluk** [comment]
Where have you seen fixes concat-ed?

**Comment by shlomizadok** [comment]
In the report's html?
What is your proposal to return all the fixes for rule?

**Comment by isimluk** [comment]
The fixes are not simply concated in the report's html. They are presented as a list of alternatives. Bad things happens, when you simply concat anaconda remediation script with bash remediation script.

I think `fixes` function should return list of `Xccdf:Fix`.

Then, the user of this library has an option to select the best applicable fix.

**Comment by shlomizadok** [comment]
Added `Xccdf::Fix`

**Comment by isimluk** [comment]
I have resolved the merge conflict manually. And cherry-picked your commits.

Thank You!

**Pull request closed without merging**
